global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus's own metrics

  - job_name: 'fastapi'
    metrics_path: '/metrics'  # The endpoint for FastAPI metrics
    static_configs:
      - targets: ['app:8000']  # Update with your FastAPI app host and port