global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ['fastapi_app:8000']  # Make sure this matches the FastAPI service name
    metrics_path: /metrics  # Ensure this matches the endpoint you set in FastAPI
